#!/bin/bash
clear

# Definindo parametros do MySQL
echo "  -- Definindo parametros do MySQL ..."
DB_NAME='DBNAME'
DB_USER='DBUSER'
DB_PASS='DBPASS'
DB_PARAM='--add-drop-table --add-locks --extended-insert --single-transaction -quick'

# Definindo parametros do sistema
echo "  -- Definindo parametros do sistema ..."
DATE=`date +%Y-%m-%d`
MYSQLDUMP=/usr/bin/mysqldump
BACKUP_DIR=/Backup/MySQL/Dumps
BACKUP_NAME=mysql-$DATE
BACKUP_TAR=mysql-$DATE.tar

# Gerando schema sql
echo "  -- Gerando Schema da base de dados $DB_NAME em $BACKUP_DIR/$BACKUP_NAME-0-schema ..."
$MYSQLDUMP -B "$DB_NAME" -u"$DB_USER" -p"$DB_PASS" --no-data > $BACKUP_DIR/$BACKUP_NAME-0-schema.sql

# Gerando arquivo sql
echo "  -- Gerando Backup da base de dados $DB_NAME em $BACKUP_DIR/$BACKUP_NAME-1-config ..."
$MYSQLDUMP -B "$DB_NAME" $DB_PARAM -u"$DB_USER" -p"$DB_PASS" > $BACKUP_DIR/$BACKUP_NAME-1-config.sql

# Compactando arquivo em tar
echo "  -- Compactando arquivo em tar ..."
tar -cf $BACKUP_DIR/$BACKUP_TAR -C $BACKUP_DIR $BACKUP_NAME-{0-schema.sql,1-config.sql} --remove-files

# Compactando arquivo em bzip2
echo "  -- Compactando arquivo em bzip2 ..."
bzip2 $BACKUP_DIR/$BACKUP_TAR

# Excluindo backups antigos
echo "  -- Excluindo backups com mais de 7 dias ..."
find $BACKUP_DIR/* -mtime +7 -delete

# Excluindo arquivos desnecessarios
#echo "  -- Excluindo arquivos desnecessarios ..."
#rm -rf $BACKUP_DIR/$BACKUP_NAME
