#!/bin/bash
clear

echo "Limpa LOGs"

echo > /var/log/alternatives.log ; echo > /var/log/apache2/access.log ; echo > /var/log/apache2/error.log ; echo > /var/log/apache2/other_vhosts_access.log ; echo > /var/log/apache2/virtual.host.access.log ; echo > /var/log/apache2/virtual.host.error.log ; echo > /var/log/apache2/www-access.log ; echo > /var/log/apache2/www-error.log ; echo > /var/log/alternatives.log ; echo > /var/log/apache2/access.log ; echo > /var/log/apache2/error.log ; echo > /var/log/apache2/other_vhosts_access.log ; echo > /var/log/apache2/virtual.host.access.log ; echo > /var/log/apache2/virtual.host.error.log ; echo > /var/log/apache2/www-access.log ; echo > /var/log/apache2/www-error.log ; echo > /var/log/mysql.log ; echo > /var/log/syslog ; echo > /var/log/udev ; echo > /var/log/wtmp ; echo > /var/log/Xorg.0.log

rm -rf /var/log/alternatives.log.* ; rm -rf /var/log/apache2/access.log.* ; rm -rf /var/log/apache2/error.log.* ; rm -rf /var/log/apache2/other_vhosts_access.log.* ; rm -rf /var/log/apache2/virtual.host.access.log.* ; rm -rf /var/log/apache2/virtual.host.error.log.* ; rm -rf /var/log/apache2/www-access.log.* ; rm -rf /var/log/apache2/www-error.log.* ; rm -rf /var/log/aptitude.1.gz ; rm -rf /var/log/auth.log.* ; rm -rf /var/log/btmp.* ; rm -rf /var/log/dpkg.log.* ; rm -rf /var/log/kern.log.* ; rm -rf /var/log/mail.err.* ; rm -rf /var/log/mail.log.* ; rm -rf /var/log/mysql/access.log.* ; rm -rf /var/log/mysql/error.log.* ; rm -rf /var/log/mysql/redis-server.log.* ; rm -rf /var/log/mysql.log.* ; rm -rf /var/log/syslog.*

rm -rf /var/log/journal/*
